# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev250+g18326b9.d20230207'
__version_tuple__ = version_tuple = (0, 1, 'dev250', 'g18326b9.d20230207')
